Traceback (most recent call last):
  File "/Users/mmcc/opt/miniconda3/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/mmcc/opt/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/mmcc/opt/miniconda3/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/mmcc/opt/miniconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/mmcc/opt/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/mmcc/opt/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/mmcc/opt/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np

in_file = open("data_files/parab_t_and_y.txt", "r")
t_list = []
y_list = []
line = in_file.readline()        # read in the first line
while len(line) > 1:             # keep doing loop until there's no more data in the file
    line_list = line.split(",")  # split the string at each comma
    t = float(line_list[0])      # convert time string to a float
    y = float(line_list[1])      # convert position string to a float
    t_list.append(t)       
    y_list.append(y)
    line = in_file.readline()
    
# everything below here we'll worry about next week...
import matplotlib.pyplot as plt
t_arr = np.array(t_list)         
y_arr = np.array(y_list)         

fig = plt.figure(figsize=(8,4))
plt.plot(t_arr, y_arr, 'o')
plt.xlabel('time (s)')
plt.ylabel('y position (m)')
plt.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[14], line 16[0m
[1;32m     13[0m     line [38;5;241m=[39m in_file[38;5;241m.[39mreadline()
[1;32m     15[0m [38;5;66;03m# everything below here we'll worry about next week...[39;00m
[0;32m---> 16[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[1;32m     17[0m t_arr [38;5;241m=[39m np[38;5;241m.[39marray(t_list)         
[1;32m     18[0m y_arr [38;5;241m=[39m np[38;5;241m.[39marray(y_list)         

[0;31mModuleNotFoundError[0m: No module named 'matplotlib'

